### ISSUE TITLE
Explicit forks

### ISSUE THREAD

**Issue by ODiogoSilva** [ODiogoSilva/assemblerflow#10]
Here is a proposal for an explicit forking system of any processes that can be set at run time by the user without any special requirements in the Process `class`.  The focus of this system should be in simplicity and readability for the user. 

## Proposal 1

A linear pipeline is currently defined simply by:

```
A B C
```

Forks could be initiated by `()` and different "lanes" could be separated by a special character like "`,`" or "`|`". For instance, forking the `A` process into two, could be simply:

```
A (B | C)
```

Process `A` could be forked N times, by separating each process by the `|` special character.

```
A (B | C | D | E)
```

Each "lane" created by the fork, can then continue normally in a linear fashion. If we want to attach more processes after the `B` fork, this could be done like:

```
A (B Y Z | C | D | E)
```

Subsequent forks could be done using the `()` again:

```
A (B | C ( E | F))
```

If we support pipelines defined via an input file, indentation could help with the readability:

```
A (
    B Z Y |
    C (
        E | 
        F
    )
)
```

A more real example would be:

```
trimmomatic fastqc (spades pilon | skesa pilon)

# or

trimmomatic fastqc (
    spades pilon |
    skesa pilon
)

```

**Comment by tiagofilipe12** [comment]
This approach is fine, however, we should be aware of complex pipelines that can difficult the reading of the pipeline. One way to ease that would be to use a new-line delimited type as you mentioned. But in summary, we should:

1. Implement this type of pipeline nomenclature to the `-t` option.
2. Allow the `-t` option to read from a file.
3. Enable new line delimited type of file.
