### ISSUE TITLE
Add real world test to .travis.yml

### ISSUE THREAD

**Issue by tseemann** [ODiogoSilva/assemblerflow#41]
Maybe download a read set and a scheme and run allele caller on it?

Will need skesa binary - spades is too slow to TRAVIS to run in time.

**Comment by ODiogoSilva** [comment]
I would love to have some field tests automatically executed on assemblerflow to make sure the assembled pipelines are correct and running as expected. However, we have many modules and module combinations, many of which may take some time to run. Even a simple skesa + chewbbaca run would take about 5-10 min depending on the input data and schema, and this would take a tool on our CI service, which is triggered at every commit.

I'm open to alternatives to perform some "endurance" tests that test the actual resulting pipeline. Perhaps using another CI service to perform the field tests upon a manual trigger?

**Comment by tseemann** [comment]
1. You don't need to use full genomes.  Cut the first 100kbp from some genomes and generate low coverage (20x) synthetic reads (using `wgsim` say).  Skesa will be fast in this case. Sure you'll gets lots of `LNF` but that's fine.

2. CI is only triggered for each push not commit?

**Comment by ODiogoSilva** [comment]
> CI is only triggered for each push not commit?

Yes, sorry that's what I meant. 

That could be a nice strategy. However, most processes rely on docker images, which means that in a typical travis build, it would have to download the images before running. I still haven't spend much time on this, but perhaps having CI with [codeship](https://codeship.com/) for the field tests would be a nice solution. It seems to have native docker support, so it might be worth checking.

**Comment by tseemann** [comment]
You have a good point about the Docker pulling.  It's a hard problem.
