### ISSUE TITLE
assemblerflow_utils not in templates folder

### ISSUE THREAD

**Issue by kristyhoran** [ODiogoSilva/assemblerflow#44]
When I run assemblerflow to generate a pipeline with --include-templates the assemblerflow_utils folder does not appear. I have been simply getting from GitHub each time I need it, but thought maybe I should let you know! Thanks
Cheers
Kristy

**Comment by tiagofilipe12** [comment]
Hi @kristyhoran, using git clone to get assemblerflow will require you to do:

```
cd assemblerflow 
git submodule add https://github.com/ODiogoSilva/templates.git templates
```

To get the templates. 

Using pip3 install this should not be a problem.
Hope it helps.

**Comment by ODiogoSilva** [comment]
Given the age of this issue, I'm closing it. Let us know of any other problems.
